# Generated by Django 5.1.15 on 2026-01-14 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('origin', models.CharField(help_text='Autor, banda, estúdio ou realizador', max_length=200)),
                ('media_type', models.CharField(choices=[('GAME', 'Game'), ('LIVRO', 'Livro'), ('MUSICA', 'Música'), ('FILME', 'Filme'), ('SERIE', 'Série'), ('ANIME', 'Anime')], default='GAME', max_length=10)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('EM_CURSO', 'Em curso'), ('CONCLUIDO', 'Concluído'), ('ABANDONADO', 'Abandonado')], default='BACKLOG', max_length=20)),
                ('rank', models.IntegerField(help_text='Nota pessoal de 0 a 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
